services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    environment:
      - IP6_PROVIDER=none
      - CLOUDFLARE_API_TOKEN
      - DOMAINNS=
      - PROXIED=
