services:
  foundry:
    image: felddy/foundryvtt:release
    container_name: foundry
    restart: unless-stopped
    ports:
      - "30000:30000"
    volumes:
      - /docker/foundry/data:/data
    env_file:
      - .env
    networks:
      - foundry_default

networks:
  foundry_default:
    external: true
