services:
  foundry:
    image: felddy/foundryvtt:13
    container_name: foundry
    restart: unless-stopped
    ports:
      - "30000:30000"
    volumes:
      - /docker/foundry/data:/data
    env_file:
      - .env
    environment:
      - FOUNDRY_USERNAME
      - FOUNDRY_PASSWORD
      - FOUNDRY_ADMIN_KEY
    networks:
      - foundry_default

networks:
  foundry_default:
    external: true
